Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Project5.Models;

//Aubre Farnbach (Wright) Sectoin 2 Group 1
//Receives cart object as a constructer argument to create a simple view with a cart overview

namespace Project5.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Views/Shared/BookSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!--Aubrey Farnbach (Wright) Section 2 group 1
    This partial view contains the table contents with the book information-->

@model Book

<tr>
    <td>
        @Model.Title
        <form id="@Model.Isbn" asp-page="/Purchase" method="post">
            <input type="hidden" asp-for="Isbn" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <span class="card-text p-1">
                <button type="submit" class="btn-sucess btn-sm pull-right" style="float:right">
                    Purchase
                </button>
            </span>

        </form>
    </td>
    <!--Presents full name-->
    <td>@Model.AuthorFirst @Model.AuthorLast</td>
    <td>@Model.Publisher</td>
    <!--Presents fiction/non-fiction and the specific category together in a list-->
    <td>@Model.ClassificationCategoryA, @Model.ClassificationCategoryB</td>
    <!--formats with dollar sign-->
    <td>$@Model.Price</td>
    <td>@Model.Isbn</td>
    <td>@Model.Pages</td>
</tr>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!--Aubrey Farnbach (Wright) Section 2 Group 1-->
    <!--Bootstrap styling on the column sizes, outline, top and bottom navs-->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Book Store</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>

    <!--<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <span class="border border-primary m-1 p-1">
                    <a class="navbar-brand text-center" asp-area="" asp-controller="Home" asp-action="Index">Book Store</a>
                </span>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <vc:cart-summary />
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item">
                        <img width="70" src="~/img/1200px-Closed_Book_Icon.svg.png" />
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <div class="text-center">
        <h1 class="display-4">Book Store Home</h1>
    </div> -->

    <div class="container">
        <!--This class sets up the pages to be organized by column-->
        <main role="main" class="pb-3">
            <div class="row m-1 p-1">
                @RenderBody()
            </div>
        </main>
    </div>

    <!--Bootstrap footer-->
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Book Store - Aubrey Farnbach (Wright)</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>